service: serverless-modern
provider:
  name: aws
  runtime: nodejs6.10
package:
    include:
        - build.js
functions:
  app:
    handler: build.hello
    events:
      - http:
          path: app
          method: get
          cors: true
