service: serverless-modern
provider:
  name: aws
  runtime: nodejs6.10
package:
    include:
        - build/**
        - handler.js
functions:
  app:
    handler: handler.app
    events:
      - http:
          path: app
          method: get
          cors: true
