service: serverless-modern
provider:
  name: aws
  runtime: nodejs6.10
package:
    include:
        - build.js
functions:
  hello:
    handler: build.hello
    events:
      - http:
          path: /
          method: get
          cors: true
plugins:
  - serverless-offline
